name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ghrunner

    env:
      AZURE_LOCATION: usgovvirginia
      AZURE_RESOURCE_GROUP: aaav-github-rg

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS2 }}
        environment: 'azureusgovernment'
        enable-AzPSSession: true 

    - name: Install Az PowerShell module
      run: |
        Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber
      shell: pwsh

    - name: Run PowerShell script
      run: ./Invoke-TestsOnGitHub.ps1
      shell: pwsh

    - name: Run PowerShell script to build module
      if: success()
      run: ./Invoke-BuildProcess.ps1
      shell: pwsh

    - name: Install PowerShellGet module
      if: success()
      run: |
        Install-Module -Name PowerShellGet -Force -Scope CurrentUser -AllowClobber
      shell: pwsh

    - name: Publish module to PowerShell Gallery
      if: success()
      run: |
        $apiKey = "${{ secrets.POWERSHELL_GALLERY_API_KEY }}"
        Publish-Module -Path ./_build/AzureAndADValidation -Repository PSGallery -NuGetApiKey $apiKey
      shell: pwsh