name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    env:
      AZURE_LOCATION: usgovvirginia
      AZURE_RESOURCE_GROUP: aaav-github-rg

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS2 }}
        environment: 'usgovernment'
        enable-AzPSSession: true 

    - name: Install Az PowerShell module
      run: |
        Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber
      shell: pwsh

    - name: Run PowerShell script
      run: ./Invoke-AllTestsButADIntegration.ps1
      shell: pwsh
